TOP = ..
include $(TOP)/configure/CONFIG_APP
#-----------------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

DBDINC = cvtRecord menuCvtMethod menuCvtInitState

LIB_SRCS = cvtRecord.c

LIBRARY_IOC += cvtRecord

include $(TOP)/configure/RULES
#-----------------------------------------------
#  ADD RULES AFTER THIS LINE
